[phases.setup]
cmds = ["echo 'Setup complete'"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python backend/flask_app.py"
